#!/bin/bash
yum -y update
wget -P /root/ http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
rpm -Uvh /root/remi-release-6*.rpm
wget -P /root/ http://ftp.riken.jp/Linux/centos/6/SCL/x86_64/scl-utils/scl-utils-20120927-11.el6.centos.alt.x86_64.rpm
rpm -Uvh /root/scl-utils-20120927-11.el6.centos.alt.x86_64.rpm
yum -y install nginx mysql varnish git php56-php.x86_64 php56-php-bcmath.x86_64 php56-php-cli.x86_64 php56-php-common.x86_64 php56-php-devel.x86_64 php56-php-fpm.x86_64 php56-php-gd.x86_64 php56-php-intl.x86_64 php56-php-mbstring.x86_64 php56-php-mcrypt.x86_64 php56-php-mysqlnd.x86_64 php56-php-odbc.x86_64 php56-php-opcache.x86_64 php56-php-pdo.x86_64 php56-php-pear.noarch php56-php-pecl-ncurses.x86_64 php56-php-pecl-redis.x86_64 php56-php-soap.x86_64 php56-php-xml.x86_64 php56-php-xmlrpc.x86_64
groupadd www-data
useradd -g www-data www-data
chown -R www-data:www-data /opt/remi
ln -s /opt/remi/php56/root/etc /etc/php
ln -s /opt/remi/php56/root/var/log/php-fpm /var/log/php-fpm
ln -s /usr/bin/php56 /usr/bin/php
curl -sS https://getcomposer.org/installer | php
mv /opt/codedeploy-agent/composer.phar /usr/bin/composer
mv /etc/php/php-fpm.d/www.conf /etc/php/php-fpm.d/www.conf.bk
mv /etc/php/php.ini /etc/php/php.ini.bk
mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bk
mkdir /var/www/magento
chmod -R 777 /var/www/magento
chown -R www-data:www-data /var/www/magento
chown -R www-data:www-data /var/log/nginx
